import { StyleSheet, Platform, StatusBar } from 'react-native';

// Android Material Design Typography Scale
const TYPOGRAPHY = {
  // Headlines
  headline1: {
    fontSize: 96,
    fontWeight: '300',
    letterSpacing: -1.5,
  },
  headline2: {
    fontSize: 60,
    fontWeight: '300',
    letterSpacing: -0.5,
  },
  headline3: {
    fontSize: 48,
    fontWeight: '400',
    letterSpacing: 0,
  },
  headline4: {
    fontSize: 34,
    fontWeight: '400',
    letterSpacing: 0.25,
  },
  headline5: {
    fontSize: 24,
    fontWeight: '400',
    letterSpacing: 0,
  },
  headline6: {
    fontSize: 20,
    fontWeight: '500',
    letterSpacing: 0.15,
  },
  // Subtitles
  subtitle1: {
    fontSize: 16,
    fontWeight: '400',
    letterSpacing: 0.15,
  },
  subtitle2: {
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 0.1,
  },
  // Body text
  body1: {
    fontSize: 16,
    fontWeight: '400',
    letterSpacing: 0.5,
  },
  body2: {
    fontSize: 14,
    fontWeight: '400',
    letterSpacing: 0.25,
  },
  // Buttons, labels
  button: {
    fontSize: 14,
    fontWeight: '500',
    letterSpacing: 1.25,
    textTransform: 'uppercase',
  },
  caption: {
    fontSize: 12,
    fontWeight: '400',
    letterSpacing: 0.4,
  },
  overline: {
    fontSize: 10,
    fontWeight: '400',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
  },
};

// Enhanced Android font family selection
const FONT_FAMILY = Platform.select({
  android: {
    regular: 'Roboto',
    medium: 'Roboto-Medium',
    light: 'Roboto-Light',
    thin: 'Roboto-Thin',
  },
  ios: {
    regular: 'San Francisco',
    medium: 'San Francisco',
    light: 'San Francisco',
    thin: 'San Francisco',
  },
  default: {
    regular: 'System',
    medium: 'System',
    light: 'System',
    thin: 'System',
  },
});

// Define COLORS if not already defined globally
const COLORS = {
  primary: '#ff0000',
  secondary: '#00875A',
  // Add other colors used in styles if needed
  white: '#fff',
  lightGrey: '#eee',
  grey: '#ccc',
  darkGrey: '#666',
  black: '#333',
  error: '#F44336',
  warning: '#FF9800',
  success: '#4CAF50',
  info: '#2196F3',
  favorite: '#FFC107',
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F5F8FA',
  },
  text: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#333',
    marginBottom: 8,
    marginTop: 8,
  },
  Logintext: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.medium,
    color: '#333',
    marginBottom: 8,
    marginTop: 16,
  },
  datePickerButton: {
    backgroundColor: '#fff',
    padding: 5,
    marginHorizontal: 15,
    borderRadius: 30,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingLeft: 20,
    paddingTop: 10,
    marginBottom: 10,
  },
  datePickerButtonText: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    marginBottom: 10,
    justifyContent: 'center',
    color: '#555',
  },
  signup_title: {
    ...TYPOGRAPHY.headline6,
    fontFamily: FONT_FAMILY.medium,
    textAlign: 'center',
    marginBottom: 20,
    marginTop: 20,
  },
  signup_text: {
    ...TYPOGRAPHY.caption,
    fontFamily: FONT_FAMILY.regular,
    marginBottom: 10,
    marginLeft: 30,
    color: '#555',
  },
  image: {
    width: '100%',
    height: '50%',
    top: -80,
    resizeMode: 'contain',
  },
  tabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginVertical: 20,
    top: -50,
  },
  addPlantTabContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 20,
    top: -50,
  },
  monitorTabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginVertical: 20,
  },
  tab: {
    paddingVertical: 10,
    top: 0,
  },
  selectParameterText: {
    ...TYPOGRAPHY.caption,
    fontFamily: FONT_FAMILY.regular,
    color: "#000",
  },
  tabText: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#000',
  },
  activeTabText: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.medium,
    color: COLORS.primary,
    borderBottomWidth: 2,
    borderBottomColor: COLORS.primary,
  },
  sample: {
    borderColor: '#555',
    borderWidth: 2,
  },  
  Logininput: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 30,
    padding: 12,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#333',
    marginBottom: 24,
    shadowColor: '#0003',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 30,
    paddingHorizontal: 12,
    marginBottom: 24,
    shadowColor: '#0003',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    minHeight: 48,
  },
  inputIcon: {
    marginRight: 10,
    width: 20,
  },
  LogininputWithIcon: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 0,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#333',
    backgroundColor: 'transparent',
  },
  inputWithIconContainer: {
    position: 'relative',
    marginBottom: 24,
  },
  LoginInputWithInlineIcon: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 30,
    padding: 12,
    paddingLeft: 45,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#333',
    shadowColor: '#0003',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  LoginInputWithDoubleIcon: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 30,
    padding: 12,
    paddingLeft: 45,
    paddingRight: 45,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#333',
    shadowColor: '#0003',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  inlineInputIcon: {
    position: 'absolute',
    left: 15,
    top: 14,
    zIndex: 1,
  },
  eyeIconContainer: {
    position: 'absolute',
    right: 15,
    top: 14,
    zIndex: 1,
    padding: 2,
  },
  input: {
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    padding: 12,
    fontSize: 16,
    color: '#333',
    marginBottom: 16,
    shadowColor: '#0003',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  plantInput: {
    top: -50,
    height: 50,
    marginHorizontal: 15,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 30,
    marginBottom: 10,
  },
  signup_input: {
    height: 50,
    marginHorizontal: 15,
    borderColor: '#ccc',
    borderWidth: 1,
    borderRadius: 30,
    marginTop: 10,
    marginBottom: 10,
    textAlignVertical: "center",
    paddingLeft: 25,
  },
  linkContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 32,
    marginHorizontal: 15,
  },
  linkText: {
    color: '#ff0000',
    ...TYPOGRAPHY.body2,
    fontFamily: FONT_FAMILY.regular,
  },
  button: {
    backgroundColor: '#ff0000',
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    marginBottom: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  buttonText: {
    color: 'white',
    ...TYPOGRAPHY.button,
    fontFamily: FONT_FAMILY.medium,
  },
  signup_button: {
    backgroundColor: '#ff0000',
    paddingVertical: 15,
    marginHorizontal: 15,
    marginTop: 40,
    borderRadius: 30,
    alignItems: 'center',
    marginBottom: 20,
    height: 55,
  },
  registerText: {
    top: -40,
    color: '#000',
    textAlign: 'center',
    paddingBottom: 50,
  },
  centerContainer: {
    justifyContent: 'center',
    top: 200,
    alignItems: 'center',
    width: '100%',
  },
  scrollView: {
    marginVertical: 20,
  },
  scrollViewContent: {
    padding: 20,
    paddingBottom: 50,
  },
  logoContainer: {
    backgroundColor: '#FFF',
    padding: 20,
    borderRadius: 8,
    marginHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    marginBottom: 10,
  },
  logoPlaceholder: {
    width: 100,
    height: 100,
    borderRadius: 50,
    overflow: 'hidden',
    backgroundColor: 'transparent',
  },
  logoImage: {
    width: '100%',
    height: '100%',
    borderRadius: 50,
  },
  logoPlaceholderText: {
    fontSize: 18,
    color: '#fff',
    fontWeight: 'bold',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    padding: 8,
    borderRadius: 4,
    zIndex: 1,
  },
  logoText: {
    fontSize: 18,
    fontWeight: 'bold',
  },
  progressBarContainer: {
    height: 5,
    width: '100%',
    backgroundColor: '#E0E0E0',
    borderRadius: 2,
    marginVertical: 20,
  },
  progressBar: {
    width: '30%',
    height: '100%',
    backgroundColor: '#3B5998',
    borderRadius: 2,
  },
  appBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    height: 56,
    backgroundColor: '#fff',
    borderBottomWidth: 0,
  },
  appBarTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#000',
  },
  iconButton: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    backgroundColor: '#fff',
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 12,
    height: 40,
  },
  searchIcon: {
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#000',
    padding: 0,
    height: '100%',
  },
  totalPlantsContainer: {
    backgroundColor: '#FFF',
    padding: 15,
    borderRadius: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    marginHorizontal: 15,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
    marginBottom: 20,
  },
  totalPlantsTitle: {
    fontSize: 16,
    marginLeft: 10,
    color: '#000',
  },
  heading: {
    fontSize: 24,
    fontWeight: 'bold',
    marginBottom: 10,
    textAlign: 'center',
  },
  line: {
    height: 1,
    backgroundColor: '#CCC',
    marginVertical: 10
  },
  plantStatusContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  plantStatusText: {
    fontSize: 16,
    marginLeft: 10,
    marginBottom: 10,
  },
  totalPlantsHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  menuItem: {
    marginHorizontal: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#fff',
    borderRadius: 10,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
  },
  menuText: {
    flex: 1,
    fontSize: 16,
    marginLeft: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    elevation: 2,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
  },
  headerSubtitle: {
    fontSize: 16,
    color: 'gray',
  },
  tab: {
    paddingVertical: 10,
    paddingHorizontal: 15,
  },
  tabText: {
    fontSize: 16,
    color: '#000',
  },
  noAlertContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noAlertImage: {
    width: 100,
    height: 100,
    marginBottom: 20,
  },
  noAlertText: {
    fontSize: 20,
    color: '#A9A9A9',
  },
  noPlantContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  noPlantText: {
    fontSize: 20,
    color: '#A9A9A9',
  },
  appBarIcon: {
    padding: 10,
  },
  tabBarContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 10,
    backgroundColor: '#FFF',
  },
  tabBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingVertical: 10,
    backgroundColor: '#FFF',
  },
  arrowIcon: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    marginLeft: 30,
  },
  watchlistContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    backgroundColor: '#FFF',
    borderRadius: 12,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
    marginBottom: 20,
  },
  watchlistLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  watchlistText: {
    fontSize: 16,
    color: '#000',
    marginLeft: 8,
  },
  arrowIcon: {
    color: '#757575',
  },
  calendarContainer: {
    marginVertical: 20,
    marginBottom: 150,
    backgroundColor: '#FFF',
    borderRadius: 8,
    padding: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    marginHorizontal: 15,
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  changeImageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 10,
    padding: 10,
    borderRadius: 8,
  },
  removeImageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    borderRadius: 8,
  },
  filterContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 10,
  },
  filterButton: {
    backgroundColor: '#FFDCDC',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
  },
  filterText: {
    color: '#FFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  addplantTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    textAlign: 'center',
    flex: 1,
  },
  imageUploadContainer: {
    width: '100%',
    height: 200,
    borderRadius: 12,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 24,
    marginTop: 10,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: '#ddd',
    shadowColor: '#0003',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  plantImage: {
    width: '100%',
    height: '100%',
  },
  imagePlaceholder: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  imagePlaceholderText: {
    color: '#999',
    marginTop: 8,
    fontSize: 16,
  },
  plantCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 12,
    padding: 16,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  plantCardImage: {
    width: '100%',
    height: 150,
    borderRadius: 8,
    marginBottom: 12,
  },
  plantCardContent: {
    flex: 1,
  },
  plantName: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  plantLocation: {
    fontSize: 16,
    color: '#666',
  },
  expandedContent: {
    marginTop: 15,
    alignItems: 'center',
    width: '100%',
  },
  emptyState: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyStateText: {
    marginTop: 12,
    fontSize: 16,
    color: '#666',
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ff0000',
    padding: 8,
    borderRadius: 4,
    marginTop: 12,
    alignSelf: 'flex-start',
  },
  editButtonText: {
    color: '#fff',
    marginLeft: 8,
    ...TYPOGRAPHY.body2,
    fontFamily: FONT_FAMILY.medium,
  },
  profileSection: {
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
    paddingVertical: 20,
  },
  profileImageContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  profileImage: {
    width: 250,
    height: 250,
    borderRadius: 200,
  },
  headerTitle: {
    ...TYPOGRAPHY.headline5,
    fontFamily: FONT_FAMILY.medium,
    marginBottom: 4,
    textAlign: 'center',
  },
  headerSubtitle: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#666',
    marginBottom: 16,
    textAlign: 'center',
  },
  imageButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 10,
  },
  imageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#ff0000',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 20,
    gap: 8,
  },
  deleteButton: {
    backgroundColor: '#666',
  },
  buttonText: {
    color: 'white',
    ...TYPOGRAPHY.body2,
    fontFamily: FONT_FAMILY.medium,
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 8,
  },
  menuText: {
    flex: 1,
    marginLeft: 16,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'flex-start',
  },
  modalContent: {
    backgroundColor: '#fff',
    marginTop: 150,
    marginHorizontal: 20,
    borderRadius: 8,
    padding: 16,
  },
  modalItem: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  modalItemText: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#333',
  },
  selectedModalItem: {
    color: '#ff0000',
    fontWeight: 'bold',
  },
  sortTabItem: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 25,
  },
  sortTabText: {
    fontSize: 10,
    color: '#666',
    marginRight: 2,
  },
  radioGroup: {
    marginBottom: 20,
  },
  radioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  radio: {
    marginHorizontal: 10,
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#000',
    marginRight: 10,
  },
  radioSelected: {
    marginHorizontal: 10,
    backgroundColor: '#FF0000',
    borderColor: '#FFDCDC',
  },
  text2: {
    fontSize: 16,
    marginLeft: 15,
    marginTop: 15,
    color: '#666',
    marginBottom: 5,
    fontWeight: '500',
  },
  radioText: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#333',
  },
  moreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginVertical: 8,
  },
  moreButtonText: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#666',
    marginRight: 4,
  },
  currencySelector: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 8,
    marginBottom: 16,
  },
  currencyText: {
    ...TYPOGRAPHY.headline6,
    fontFamily: FONT_FAMILY.regular,
    top: -50,
    marginHorizontal: 30,
    color: '#333',
  },
  alertSafeArea: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight - 10 : 0,
  },
  alertAppBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
    top: -20,
    paddingVertical: 8,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  alertTitle: {
    ...TYPOGRAPHY.headline6,
    fontFamily: FONT_FAMILY.medium,
    color: '#000',
  },
  alertTabContainer: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginVertical: 20,
    top: -30,
  },
  componentContainer: {
    marginBottom: 20,
    borderRadius: 8,
    backgroundColor: '#fff',
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
  },
  toggleButton: {
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignItems: 'center',
  },
  toggleText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  settingSection: {
    marginBottom: 20,
  },
  toggleButton: {
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    alignItems: 'center',
    marginHorizontal: 16,
  },
  toggleButtonText: {
    color: 'white',
    fontWeight: 'bold',
  },
  settingsContainer: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  settingOption: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  settingLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  settingText: {
    fontSize: 16,
    color: '#333',
    marginLeft: 12,
  },
  settingRight: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  settingRightText: {
    fontSize: 16,
    color: '#999',
    marginRight: 8,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
    marginTop: 20,
    backgroundColor: '#fff',
    gap: 8,
  },
  logoutText: {
    color: '#FF6B6B',
    fontSize: 16,
    fontWeight: '500',
  },
  reg_safeArea: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight || 0 : 0,
  },
  reg_container: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  reg_scrollContainer: {
    flex: 1,
  },
  reg_scrollContent: {
    flexGrow: 1,
    paddingBottom: 30,
  },
  reg_header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 9,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  reg_androidHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 4,
    paddingVertical: 0,
    backgroundColor: '#fff',
    height: 56,
    elevation: 0,
    borderBottomWidth: 1,
    borderBottomColor: '#e0e0e0',
  },
  reg_headerText: {
    ...TYPOGRAPHY.headline6,
    fontFamily: FONT_FAMILY.medium,
    color: '#333',
    textAlign: 'center',
  },
  reg_androidHeaderText: {
    ...TYPOGRAPHY.headline6,
    fontFamily: FONT_FAMILY.medium,
    color: '#212121',
    marginLeft: 32,
    flex: 1,
    lineHeight: 24,
  },
  backButton: {
    padding: 12,
    borderRadius: 20,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 44,
    minHeight: 44,
  },
  androidBackButton: {
    padding: 12,
    borderRadius: 24,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    width: 48,
    height: 48,
    marginLeft: 4,
  },
  reg_form: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 20,
    minHeight: 600,
  },
  reg_label: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.medium,
    color: '#333',
    marginBottom: 6,
    marginTop: 12,
  },
  reg_input: {
    height: 48,
    backgroundColor: '#fff',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingLeft: 12,
    paddingRight: 45,
    marginBottom: 12,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: 'black',
    flex: 1,
  },
    reg_input_delete: {
    height: 48,
    backgroundColor: '#fff',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingLeft: 45,
    paddingRight: 45,
    marginBottom: 12,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: 'black',
    flex: 1,
  },
  reg_inputContainer: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  reg_inputWithIcon: {
    height: 48,
    backgroundColor: '#fff',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingLeft: 45,
    paddingRight: 12,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: 'black',
    flex: 1,
  },
  reg_inputWithDoubleIcon: {
    height: 48,
    backgroundColor: '#fff',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingLeft: 45,
    paddingRight: 45,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: 'black',
    flex: 1,
  },
  reg_inputIcon: {
    position: 'absolute',
    left: 15,
    top: 14,
    zIndex: 1,
  },
  reg_eyeButton: {
    position: 'absolute',
    right: 15,
    top: 9,
    padding: 5,
    zIndex: 1,
  },
  reg_dateInput: {
    height: 48,
    backgroundColor: '#fff',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingHorizontal: 15,
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
  },
  reg_dateInputWithIcon: {
    height: 48,
    backgroundColor: '#fff',
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#ddd',
    paddingLeft: 45,
    paddingRight: 15,
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  reg_dateInputField: {
    flex: 1,
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#333',
    paddingRight: 10,
  },
  calendarIcon: {
    position: 'absolute',
    right: 15,
    top: 13,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  reg_signupButton: {
    backgroundColor: '#ff0000',
    height: 48,
    borderRadius: 25,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 16,
  },
  reg_signupText: {
    color: '#fff',
    ...TYPOGRAPHY.button,
    fontFamily: FONT_FAMILY.medium,
  },
  reg_loginLink: {
    color: '#007AFF',
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.medium,
  },
  reg_loginContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 12,
  },
  reg_loginText: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.regular,
    color: '#666',
  },
  reg_checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 12,
    marginTop: 16,
  },
  reg_checkbox: {
    marginRight: 10,
  },
  reg_checkboxText: {
    ...TYPOGRAPHY.body1,
    fontFamily: FONT_FAMILY.medium,
    color: '#333',
  },
  reg_termsLink: {
    fontSize: 16,
    color: '#007AFF',
    fontWeight: '500',
    textDecorationLine: 'underline',
  },
  termsContainer: {
    flex: 1,
    paddingHorizontal: 20,
  },
  termsContent: {
    paddingBottom: 30,
  },
  termsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 20,
    marginTop: 10,
  },
  termsSection: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
    marginTop: 20,
    marginBottom: 10,
  },
  termsText: {
    fontSize: 16,
    color: '#666',
    lineHeight: 24,
    textAlign: 'justify',
    marginBottom: 10,
  },
  termsFooter: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    marginTop: 30,
    fontStyle: 'italic',
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    zIndex: 1000,
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: '#666',
  },
  retryButton: {
    backgroundColor: '#ff0000',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 20,
    alignSelf: 'center',
  },
  retryButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  switchButton: {
    padding: 8,
    borderRadius: 20,
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
    minWidth: 44,
    minHeight: 44,
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 40,
  },
  errorTitle: {
    fontSize: 20,
    fontWeight: '600',
    color: '#333',
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  errorText: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 22,
    marginBottom: 24,
  },
  errorButtons: {
    flexDirection: 'row',
    gap: 12,
  },
  fallbackButton: {
    backgroundColor: '#f0f0f0',
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  fallbackButtonText: {
    color: '#333',
    fontSize: 16,
    fontWeight: '600',
  },
  termsNotice: {
    backgroundColor: '#e3f2fd',
    padding: 12,
    borderRadius: 8,
    marginBottom: 20,
    borderLeftWidth: 4,
    borderLeftColor: '#2196F3',
  },
  termsNoticeText: {
    fontSize: 14,
    color: '#1976D2',
    fontWeight: '500',
  },
  // OTP Screen Styles
  otpContainer: {
    flex: 1,
    paddingHorizontal: 20,
    justifyContent: 'center',
  },
  otpContent: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  otpTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    marginBottom: 10,
    textAlign: 'center',
  },
  otpDescription: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 30,
  },
  otpEmailAddress: {
    fontWeight: '600',
    color: '#333',
  },
  otpInput: {
    width: '80%',
    height: 60,
    borderWidth: 2,
    borderColor: '#ddd',
    borderRadius: 12,
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    backgroundColor: '#fff',
    marginBottom: 30,
    letterSpacing: 8,
  },
  otpVerifyButton: {
    backgroundColor: '#ff0000',
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 25,
    width: '80%',
    alignItems: 'center',
    marginBottom: 20,
  },
  otpVerifyButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: '600',
  },
  otpHelpText: {
    fontSize: 14,
    color: '#999',
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 20,
    paddingHorizontal: 20,
  },
  otpTestButton: {
    backgroundColor: '#ff0000',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 15,
    marginTop: 20,
    alignSelf: 'center',
  },
  otpTestButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  dimBackground: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'black',
  },
  logoImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  logoOverlay: {
    ...StyleSheet.absoluteFillObject,
    justifyContent: 'center',
    alignItems: 'center',
  },
  logoOverlayText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 16,
    textAlign: 'center',
  },
  questionContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
    paddingHorizontal: 15,
    flexWrap: 'wrap',
  },
  questionIcon: {
    marginRight: 5,
  },
  questionText: {
    fontSize: 12,
    color: '#666',
    textAlign: 'center',
    flexShrink: 1,
  },
  detailsContainer: {
    marginTop: 16,
    paddingHorizontal: 15,
  },
  locationSection: {
    marginBottom: 15,
  },
  locationContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  locationButton: {
    backgroundColor: '#f5f7fa',
    padding: 12,
    borderRadius: 25,
    alignItems: 'center',
    marginHorizontal: 15,
    marginBottom: 15,
    flexDirection: 'row',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#e0e0e0',
    elevation: 1,
  },
  coordinatesContainer: {
    backgroundColor: '#f5f5f5',
    padding: 10,
    borderRadius: 5,
    marginTop: 5,
  },
  coordinatesText: {
    fontSize: 14,
    color: '#666',
    marginBottom: 5,
  },
  locationInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 15,
  },
  locationIconButton: {
    padding: 10,
    backgroundColor: '#f5f5f5',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    height: 48,
    width: 48,
    marginLeft: -58,
  },
  locationContainer: {
    marginBottom: 15,
  },
  locationInput: {
    fontSize: 14,
    paddingRight: 10,
    height: 48,
  },
  addressInput: {
    height: 80,
    textAlignVertical: 'top',
  },
  sectionTitle: {
    fontSize: 16,
    color: '#333',
    marginBottom: 10,
    marginLeft: 0,
  },
  radioGroupContainer: {
    marginLeft: 15,
    marginBottom: 8,
  },
  radioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
    marginLeft: 15,
    paddingVertical: 5,
  },
  radio: {
    height: 20,
    width: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#666',
    marginRight: 10,
  },
  radioSelected: {
    backgroundColor: '#2EAEBE',
    borderColor: '#2EAEBE',
  },
  radioText: {
    fontSize: 16,
    marginLeft: 10,
  },
  addPlantSectionTitle: {
    marginLeft: 15,
    fontSize: 16,
    marginBottom: 10,
  },
  systemTypeTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginBottom: 8,
    marginTop: 16,
  },
  systemTypeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 20,
    marginTop: 5,
  },
  systemTypeRadio: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 20,
    marginBottom: 10,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 20,
    backgroundColor: '#f5f5f5',
  },
  systemTypeText: {
    fontSize: 14,
    color: '#333',
    marginLeft: 8,
  },
  map: {
    flex: 1,
    width: '100%',
  },
  mapHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 15,
    backgroundColor: '#fff',
  },
  mapCloseButton: {
    padding: 5,
  },
  mapTitle: {
    flex: 1,
    textAlign: 'center',
    fontSize: 18,
    fontWeight: 'bold',
    marginRight: 40,
  },
  confirmLocationButton: {
    backgroundColor: '#ff0000',
    padding: 15,
    margin: 15,
    borderRadius: 25,
    alignItems: 'center',
    elevation: 2,
  },
  confirmLocationText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  separatorContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 15,
  },
  separator: {
    flex: 1,
    height: 1,
    backgroundColor: '#E0E0E0',
  },
  registerPromptContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 24,
    marginBottom: 32,
  },
  registerPromptText: {
    fontSize: 16,
    color: '#000',
  },
  registerLinkText: {
    fontSize: 16,
    fontWeight: 'bold',
  
  },
  separatorText: {
    marginHorizontal: 10,
    color: '#666',
    fontSize: 14,
  },
  googleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#fff',
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 30,
    marginHorizontal: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.2,
    shadowRadius: 1.5,
  },
  googleIcon: {
    marginRight: 10,
  },
  googleButtonText: {
    color: '#444',
    fontSize: 16,
    fontWeight: '500',
  },
  registerButton: {
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 20,
  },
  iosPickerContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderTopColor: '#e0e0e0',
    zIndex: 1000,
  },
  iosPickerHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    backgroundColor: '#f8f8f8',
  },
  iosPickerCancel: {
    color: '#007AFF',
    fontSize: 16,
  },
  iosPickerDone: {
    color: '#007AFF',
    fontSize: 16,
    fontWeight: 'bold',
  },
  reg_dateInput: {
    height: 50,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 8,
    paddingHorizontal: 15,
    marginBottom: 15,
    justifyContent: 'center',
  },
  reg_dateText: {
    color: '#000',
    fontSize: 16,
  },
  reg_datePlaceholder: {
    color: '#999',
    fontSize: 16,
  },
  formContainer: {
    width: '90%',
    alignSelf: 'center',
    paddingHorizontal: 10,
    marginTop: 100,
  },
  googleSignInButton: {
    width: '100%',
    height: 48,
    marginVertical: 15,
  },
  retryButton: {
    backgroundColor: '#ff0000',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 8,
    marginTop: 20,
  },
  retryButtonText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  offlineStatusBar: {
    backgroundColor: '#f57c00',
    padding: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  offlineStatusText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: 'bold',
    marginLeft: 8,
  },
  pendingBadge: {
    backgroundColor: '#fff',
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  pendingBadgeText: {
    color: '#f57c00',
    fontSize: 10,
    fontWeight: 'bold',
  },
  pendingBadgeInline: {
    color: '#f57c00',
    fontSize: 12,
    fontStyle: 'italic',
  },
  pendingPlantCard: {
    borderLeftWidth: 5,
    borderLeftColor: '#4CAF50',
  },
  pendingUpdateCard: {
    borderLeftWidth: 5,
    borderLeftColor: '#FFC107',
  },
  buttonRow: {
    flexDirection: 'row',
    marginTop: 20,
  },
  syncTimeText: {
    color: '#666',
    fontSize: 12,
    marginTop: 10,
  },
  syncFloatingButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#ff0000',
    width: 56,
    height: 56,
    borderRadius: 28,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
    flexDirection: 'row',
  },
  syncButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    marginLeft: 2,
  },
  inputContainer: {
    position: 'relative',
    marginBottom: 16,
  },
  loadingIndicator: {
    position: 'absolute',
    right: 12,
    top: 12,
  },
  disabledInput: {
    backgroundColor: '#f5f5f5',
    color: '#999',
  },
  refreshLocationButton: {
    position: 'absolute',
    right: 12,
    top: 12,
    padding: 4,
  },
  locationButton: {
    flexDirection: 'row',
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 20,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  locationButtonText: {
    color: '#333',
    fontSize: 14,
    marginLeft: 6,
    fontWeight: '500',
  },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  loadingBox: {
    backgroundColor: 'white',
    borderRadius: 12,
    padding: 24,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    elevation: 8,
    width: '80%',
  },
  loadingText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 16,
    marginBottom: 8,
    textAlign: 'center',
  },
  loadingSubText: {
    fontSize: 14,
    color: '#666',
    textAlign: 'center',
  },
  sectionHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 24,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingBottom: 8,
  },
  cancelButton: {
    padding: 8,
  },
  cancelButtonText: {
    color: '#00875A',
    fontSize: 16,
  },
  addPlantHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    elevation: 2,
  },
  addPlantHeaderTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
  },
  addPlantCancelButton: {
    padding: 8,
  },
  addPlantCancelText: {
    color: '#00875A',
    fontSize: 16,
  },
  addPlantSectionHeader: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#333',
    marginTop: 24,
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingBottom: 8,
  },
  addPlantScrollContent: {
    padding: 16,
    paddingBottom: 50,
  },
  addPlantSaveButton: {
    backgroundColor: '#ff0000',
    borderRadius: 10,
    padding: 15,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 30,
    marginBottom: 20,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
  },
  addPlantSaveText: {
    color: 'white',
    fontSize: 18,
    fontWeight: '500',
  },
  addPlantLocationContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
  },
  addPlantLocationButton: {
    flex: 1,
    flexDirection: 'row',
    backgroundColor: '#f0f0f0',
    borderRadius: 8,
    padding: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  addPlantLocationButtonLeft: {
    marginRight: 5,
  },
  addPlantLocationButtonRight: {
    marginLeft: 5,
    backgroundColor: '#e8f4ff',
  },
  addPlantLocationTextBlue: {
    color: '#0066cc',
  },
  LoginButton: {
    backgroundColor: '#ff0000',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: 20,
    elevation: 2,
  },
  businessScreenButton: {
    backgroundColor: '#ff0000',
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 15,
    marginHorizontal: 20,
    elevation: 2,
  },
  businessName: {
    fontSize: 16,
    fontWeight: 'bold',
    textAlign: 'center',
    marginVertical: 8,
    color: '#333',
  },
  businessDescription: {
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 12,
    color: '#666',
  },
  expandedContent: {
    marginTop: 15,
    alignItems: 'center',
    width: '100%',
  },
  dashboardContainer: {
    padding: 16,
    paddingBottom: 24,
  },
  dashboardSearchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    marginHorizontal: 16,
    marginVertical: 12,
    borderWidth: 1,
    borderColor: '#ebebeb',
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
  },
  dashboardSearchIcon: {
    marginRight: 8,
    color: '#757575',
  },
  dashboardSearchInput: {
    flex: 1,
    fontSize: 15,
    color: '#333',
    paddingVertical: 4,
  },
  watchlistContainerEnhanced: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  plantDetail: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    marginHorizontal: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  watchlistLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  watchlistText: {
    fontSize: 16,
    fontWeight: '600',
    marginLeft: 12,
    color: '#252525',
  },
  totalPlantsContainerEnhanced: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  totalPlantsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  totalPlantsTitleEnhanced: {
    fontSize: 16,
    fontWeight: '600',
    color: '#252525',
  },
  lineEnhanced: {
    height: 1,
    backgroundColor: '#eeeeee',
  },
  plantStatusContainerEnhanced: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  plantStatusTextEnhanced: {
    fontSize: 15,
    marginLeft: 12,
    color: '#424242',
  },
  productionDetailsContainer: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 18,
    marginBottom: 16,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  productionDetailsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#252525',
    marginBottom: 5,
  },
  productionDetailsChart: {
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 50,
  },
  productionStatsText: {
    fontSize: 14,
    color: '#555',
    textAlign: 'center',
  },
  arrowIcon: {
    color: '#757575',
  },
  offlineIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff3e0',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 4,
    marginHorizontal: 16,
    marginVertical: 8,
  },
  offlineText: {
    color: '#f57c00',
    marginLeft: 8,
    fontSize: 14,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#666',
  },
  errorContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  errorText: {
    marginTop: 10,
    marginBottom: 20,
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
  },
  addPlantButton: {
    position: 'absolute',
    bottom: 20,
    right: 20,
    backgroundColor: '#ff0000', // Button color
    borderRadius: 50,
    padding: 15,
    elevation: 5, // Shadow effect
    alignItems: 'center',
    justifyContent: 'center',
},
  retryButton: {
    backgroundColor: '#ff0000',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 4,
  },
  retryButtonText: {
    color: 'white',
    fontWeight: '500',
  },
  yourImageStyle: {
    width: 100,
    height: 100,
    marginBottom: 20,
  },
  filterRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ff0000',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ff0000',
  },
  customizedButton: {
    backgroundColor: '#ff0000',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 25,
    alignItems: 'center',
    marginVertical: 20,
    alignSelf: 'center',
    width: '80%',
  },
  customizedButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  paramsOptionsContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  paramsOptionContainer: {
    marginBottom: 15,
    alignItems: 'center',
    width: '100%',
  },
  paramsOptionText: {
    color: '#333',
    fontSize: 16,
    textAlign: 'center',
  },
  selectedOptionText: {
    color: '#ff0000',
    fontWeight: 'bold',
  },
  customizedButton: {
    backgroundColor: '#ff0000',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 25,
    alignItems: 'center',
    marginVertical: 20,
    alignSelf: 'center',
    width: '80%',
  },
  customizedButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: 'bold',
  },
  paramsOptionsContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  paramsOptionButton: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    marginBottom: 15,
    backgroundColor: '#fff',
    width: '80%',
    alignItems: 'center',
  },
  selectedOptionButton: {
    backgroundColor: '#ff0000',
    borderColor: '#ff0000',
  },
  paramsOptionText: {
    color: '#333',
    fontSize: 16,
  },
  selectedOptionText: {
    color: '#fff',
    fontWeight: 'bold',
  },
  closeIconContainer: {
    position: 'absolute',
    top: 10,
    right: 10,
    zIndex: 1,
  },
  // Add Production Overview Styles (copied from PlantDetail)
  productionOverviewContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 10,
    // Removed background color here, assuming card style provides it
  },
  productionLeftColumn: {
    flex: 1,
    alignItems: 'center',
    marginRight: 10,
  },
  productionRightColumn: {
    flex: 1.2,
    // Align items to the start (left) for this column
    alignItems: 'flex-start',
  },
  progressGraphicContainer: {
    width: 120, // Match the size of your progressCirclePlaceholder
    height: 120, // Match the size of your progressCirclePlaceholder
    position: 'relative', // Needed for absolute positioning of children
    alignItems: 'center', // Center the placeholder if needed
    justifyContent: 'center',
    marginBottom: 10, // Or whatever spacing you had
  },
  progressCirclePlaceholder: {
    // Keep existing styles for the arc visualization (width, height, borderRadius, borderWidth, borderColor, etc.)
    // Ensure it doesn't have position: 'absolute' itself if the parent handles positioning
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 10, // Example
    borderColor: '#e0e0e0', // Example background color
    borderLeftColor: 'transparent', // Example to create an arc segment
    borderBottomColor: 'transparent', // Example to create an arc segment
    // The rotation is applied via transform in the component
  },
  progressTextContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    // Ensure this container itself does not have a transform
  },
  progressPercentText: {
    // Keep existing styles for the percentage text
    fontSize: 24,
    fontWeight: 'bold',
    color: COLORS.primary || '#00875A',
  },
  powerIcon: {
    // Optional: Adjust positioning if needed now that it's absolutely positioned
    // position: 'absolute', // Example if you need fine control
    // bottom: 5,          // Example
  },
  productionStatItem: {
    width: '100%',
    marginBottom: 8, // Reduced margin
    // Align text based on column
    // alignItems: 'center', // Center only for left column items if needed
  },
  productionStatLabel: {
    fontSize: 12, // Smaller label
    color: COLORS.darkGrey || '#666',
    marginBottom: 1,
  },
  productionStatValue: {
    fontSize: 14, // Smaller value
    fontWeight: 'bold',
    color: COLORS.black || '#333',
  },
  productionStatUnit: {
    fontSize: 11, // Smaller unit
    fontWeight: 'normal',
    color: COLORS.darkGrey || '#555',
  },

  card: { // Generic card style (if needed)
    backgroundColor: COLORS.white || '#fff',
    borderRadius: 8,
    padding: 16,
    marginHorizontal: 16, // Add horizontal margin
    marginVertical: 8, // Add vertical margin
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  menuOptionText: {
    marginLeft: 16,
    fontSize: 16,
    color: '#333',
  },
  cardTitle: {
    fontSize: 18,
  },
  loginTopContainer: {
    top:-100,
  },
  loginContainer: {
    flex: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 20,
    backgroundColor: '#fff',
  },
  loginLogoContainer: {
    alignItems: 'center',
    marginTop: '15%',
    marginBottom: '10%',
  },
  loginLogo: {
    width: 200,
    height: 80,
    resizeMode: 'contain',
  },
  loginFormContainer: {
    width: '100%',
  },
  loginButtonContainer: {
    marginTop: 20,
    width: '100%',
  },
  loginFooterContainer: {
    marginTop: 'auto',
    marginBottom: 30,
    width: '100%',
  },
  loginSeparatorContainer: {
    marginVertical: 30,
  },
  loginSocialContainer: {
    marginTop: 20,
    width: '100%',
  },
});

const filterStyles = {
  filterModalContainer: {
    flex: 1,
    backgroundColor: '#fff',
  },
  filterModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  filterModalTitle: {
    fontSize: 18,
    fontWeight: '500',
    color: '#333',
  },
  filterModalCloseText: {
    fontSize: 16,
    color: '#666',
  },
  filterModalContent: {
    padding: 16,
  },
  filterSectionTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: '#333',
    marginTop: 20,
    marginBottom: 12,
  },
  filterRadioGroup: {
    marginBottom: 16,
  },
  filterRadioButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
  },
  filterRadio: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#ddd',
    marginRight: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  filterRadioSelected: {
    borderColor: '#ff0000',
  },
  filterRadioInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ff0000',
  },
  filterRadioText: {
    fontSize: 16,
    color: '#333',
  },
  capacityRangeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  capacityInput: {
    flex: 1,
    height: 40,
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    paddingHorizontal: 12,
    fontSize: 16,
    backgroundColor: '#fff',
  },
  capacitySeparator: {
    marginHorizontal: 8,
    color: '#666',
  },
  capacityPresetsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 20,
  },
  capacityPresetButton: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#ddd',
    marginRight: 8,
    marginBottom: 8,
    backgroundColor: '#fff',
  },
  capacityPresetButtonSelected: {
    backgroundColor: '#ff0000',
    borderColor: '#ff0000',
  },
  capacityPresetText: {
    color: '#666',
    fontSize: 14,
  },
  capacityPresetTextSelected: {
    color: '#fff',
  },
  filterButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 16,
    borderTopWidth: 1,
    borderTopColor: '#eee',
    backgroundColor: '#fff',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  filterResetButton: {
    flex: 1,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 22,
    borderWidth: 1,
    borderColor: '#ddd',
    marginRight: 8,
    backgroundColor: '#fff',
  },
  filterResetText: {
    color: '#666',
    fontSize: 16,
    fontWeight: '500',
  },
  filterConfirmButton: {
    flex: 1,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 22,
    marginLeft: 8,
    backgroundColor: '#ff0000',
  },
  filterConfirmText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '500',
  },
  
  // Delete Account Screen Styles
  deleteAccountTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#333',
    textAlign: 'center',
    marginBottom: 15,
  },
  deleteAccountDescription: {
    fontSize: 16,
    color: '#666',
    textAlign: 'center',
    marginBottom: 30,
    lineHeight: 22,
    paddingHorizontal: 10,
  },
  deleteWarningContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#fff5f5',
    padding: 15,
    borderRadius: 8,
    borderLeftWidth: 4,
    borderLeftColor: '#ff3b30',
    marginVertical: 20,
  },
  deleteWarningText: {
    flex: 1,
    marginLeft: 10,
    fontSize: 14,
    color: '#ff3b30',
    lineHeight: 20,
  },
  deleteAccountButton: {
    backgroundColor: '#ff3b30',
    paddingVertical: 15,
    borderRadius: 8,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  deleteAccountButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
};

export default {
  ...styles,
  ...filterStyles,
};

// Export the typography constants, font families, and colors for use in components
export { TYPOGRAPHY, FONT_FAMILY, COLORS };